# Generated by Django 6.0.1 on 2026-03-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fa', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fa', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_fa', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(upload_to='profile/')),
                ('birthday', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('location_en', models.CharField(max_length=255, null=True)),
                ('location_fa', models.CharField(max_length=255, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('about_me', models.TextField()),
                ('about_me_en', models.TextField(null=True)),
                ('about_me_fa', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contact_info', models.CharField(help_text='Email, Telegram ID, or Phone', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Code', 'Code'), ('Zap', 'Zap'), ('Smartphone', 'Smartphone'), ('PenTool', 'PenTool')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_fa', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fa', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fa', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fa', models.TextField(null=True)),
                ('tech_stack', models.CharField(help_text='Comma separated tags e.g. React, Node.js', max_length=255)),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Visit Link')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Preview/GitHub Link')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
