# Generated by Django 6.0.1 on 2026-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_fa',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='short_description_fa',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_fa',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='language',
            field=models.CharField(
                choices=[('en', 'English'), ('fa', 'Persian')],
                default='en',
                max_length=2,
            ),
        ),
    ]
